Cocoapods development project intialization
Hipo/magpie pull request #1
Opened 2018-09-10 20:15 UTC by eraydiler

2018-09-11 17:44 UTC, taylanpince requested changes
Minor changes needed

2018-09-11 17:44 UTC, taylanpince commented on LICENSE
> +Copyright (c) 2018 eraydiler <eray.diler@gmail.com>
This should be Hipo

2018-09-11 17:44 UTC, taylanpince commented on Magpie.podspec
> +  s.homepage         = 'https://github.com/eraydiler/Magpie'
Wrong homepage

2018-09-11 17:44 UTC, taylanpince commented on Magpie.podspec
> +  s.author           = { 'eraydiler' => 'eray.diler@gmail.com' }
Please use Hipo email

2018-09-11 17:44 UTC, taylanpince commented on Magpie.podspec
> +  s.source           = { :git => 'https://github.com/eraydiler/Magpie.git', :tag => s.version.to_s }
Wrong source

2018-09-11 17:44 UTC, taylanpince commented on README.md
> +Hipo team
Please add your own name here Eray, you can also link your social media profile (i.e. Twitter) etc. if you wish

2018-09-12 12:50 UTC, sakkaras commented
@taylanpince I made a meeting with @eraydiler about the basic infrastructure and usage of the library. @eraydiler will write a prototype for what we discussed. Then you can give feedback over the prototype code.  

Is it ok for me to merge it since @eraydiler needs the project to work?

2018-09-12 13:48 UTC, taylanpince commented
@sakkaras Sounds good!

2018-09-12 13:48 UTC, taylanpince approved these changes

2018-09-12 13:48 UTC, merged